#=======================================================
# Description: Build OpenWrt using GitHub Actions
# https://github.com/Hyy2001X/AutoBuild-Actions
# Lisence: MIT
# Author: P3TERX
# Modify: Hyy2001X
#=======================================================

name: AutoBuild-NEWIFI_D2-NIGHTLY

on: 
  release:
    types: [published]

  push:
    branches:
      - master

  schedule:
    - cron: 0 11 * * *
  
  watch:
    types: [started]

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  CONFIG_FILE: Configs/NEWIFI_D2-NIGHTLY.config
  DIY_SCRIPT: Scripts/diy-script.sh
  UPLOAD_RELEASE: true
  UPLOAD_FIRMWARE: true
  UPLOAD_BIN_DIR: true
  REMOVE_OLD_RELEASE: false
  DELETE_WORKFLOW_RUNS: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
